spring:
  application:
    name: shop-gateway-web
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        #商品微服务
        - id: shop_product_route
          uri: lb://product-service
          predicates: #请求的地址
            - Path=/product-service/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter #请求数限流，名字使用默认的factory
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 4
#        #商品微服务
#        - id: shop_product_route
#          uri: lb://product-service
#          predicates: #请求的地址
#            - Path=/product-service/**
#          filters:
#            - StripPrefix=1
#            - name: Hystrix
#              args:
#                name: default
#                fallbackUri: 'forward:/defaultfallback'
  redis:
    host: 127.0.0.1
    port: 6379
server:
  port: 9000

# hystrix 信号量隔离，3秒后自动超时
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 3000
  shareSecurityContext: true

eureka:
  client:
    service-url:
      defaultZone: http://test:123456@127.0.0.1:8000/eureka/
  instance:
    prefer-ip-address: true


management:
  endpoint:
    gateway:
      enabled: true
    web:
      exposure:
        include: true